<?xml version="1.0"?>

<robot name="differential_drive_robot" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <!-- ===================== -->
  <!-- Robot Parameters      -->
  <!-- ===================== -->
  <xacro:property name="PI" value="3.14159265"/>

  <!-- Thân robot -->
  <xacro:property name="body_length" value="0.5"/>
  <xacro:property name="body_width"  value="0.3"/>  <!-- be ngang C cua robot-->
  <xacro:property name="body_height" value="0.1"/>
  <xacro:property name="body_density" value="7850.0"/> <!-- thép -->
  <xacro:property name="body_mass" value="${body_density * body_length * body_height * body_width}"/>
  <xacro:property name="body_inertia_x" value="${1.0/12.0 * body_mass * (body_height*body_height + body_width*body_width)}"/>
  <xacro:property name="body_inertia_y" value="${1.0/12.0 * body_mass * (body_length*body_length + body_height*body_height)}"/>
  <xacro:property name="body_inertia_z" value="${1.0/12.0 * body_mass * (body_length*body_length + body_width*body_width)}"/>

  <!-- Bánh xe -->
  <xacro:property name="wheel_radius" value="0.1"/>
  <xacro:property name="wheel_width"  value="0.05"/>
  <xacro:property name="wheel_separation" value="${body_width + wheel_width}"/>
  <xacro:property name="wheel_offset" value="${body_length/2 - wheel_radius}"/>
  <xacro:property name="wheel_density" value="900"/> <!-- rubber -->
  <xacro:property name="wheel_mass" value="${wheel_density * PI * wheel_radius * wheel_radius * wheel_width}"/>
  <xacro:property name="wheel_inertia_x" value="${1.0/12.0 * wheel_mass * (3*wheel_radius*wheel_radius + wheel_width*wheel_width)}"/>
  <xacro:property name="wheel_inertia_y" value="${1.0/12.0 * wheel_mass * (3*wheel_radius*wheel_radius + wheel_width*wheel_width)}"/>
  <xacro:property name="wheel_inertia_z" value="${1.0/2.0 * wheel_mass * wheel_radius * wheel_radius}"/>

  <!-- Bánh caster -->
  <xacro:property name="caster_radius" value="0.1"/>
  <xacro:property name="caster_offset" value="${body_length/2 - caster_radius}"/>
  <xacro:property name="caster_density" value="0.1"/>
  <xacro:property name="caster_mass" value="${caster_density * 4.0/3.0 * PI * caster_radius * caster_radius * caster_radius}"/>
  <xacro:property name="caster_inertia_x" value="${2.0/5.0 * caster_mass * caster_radius * caster_radius}"/>
  <xacro:property name="caster_inertia_y" value="${2.0/5.0 * caster_mass * caster_radius * caster_radius}"/>
  <xacro:property name="caster_inertia_z" value="${2.0/5.0 * caster_mass * caster_radius * caster_radius}"/>

  <!-- Điều khiển -->
  <xacro:property name="max_linear_acceleration" value="10"/>

  <!-- ===================== -->
  <!-- Links                 -->
  <!-- ===================== -->

  <!-- Thân chính -->
  <link name="body_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="${body_length} ${body_width} ${body_height}"/>
      </geometry>
      <material name="body_material">
        <color rgba="0.25 0.25 0.25 1.0"/>
      </material>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="${body_length} ${body_width} ${body_height}"/>
      </geometry>
    </collision>
    <inertial>
      <!-- Giữ 10 kg theo bản gốc -->
      <mass value="10"/>
      <inertia ixx="${body_inertia_x}" ixy="0.0" ixz="0.0"
               iyy="${body_inertia_y}" iyz="0.0" izz="${body_inertia_z}"/>
      <origin xyz="0 0 0" rpy="0 0 0"/>
    </inertial>
  </link>

  <!-- Bánh trái -->
  <link name="left_wheel_link">
    <visual>
      <origin xyz="0 0 0" rpy="1.570795 0 0"/>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
      </geometry>
      <material name="wheel_material">
        <color rgba="0 0 0 1.0"/>
      </material>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="1.570795 0 0"/>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="2"/>
      <inertia ixx="${wheel_inertia_x}" ixy="0.0" ixz="0.0"
               iyy="${wheel_inertia_y}" iyz="0.0" izz="${wheel_inertia_z}"/>
      <origin xyz="0 0 0" rpy="1.570795 0 0"/>
    </inertial>
  </link>

  <!-- Bánh phải -->
  <link name="right_wheel_link">
    <visual>
      <origin xyz="0 0 0" rpy="1.570795 0 0"/>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
      </geometry>
      <material name="wheel_material">
        <color rgba="0 0 0 1.0"/>
      </material>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="1.570795 0 0"/>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="2"/>
      <inertia ixx="${wheel_inertia_x}" ixy="0.0" ixz="0.0"
               iyy="${wheel_inertia_y}" iyz="0.0" izz="${wheel_inertia_z}"/>
      <origin xyz="0 0 0" rpy="1.570795 0 0"/>
    </inertial>
  </link>

  <!-- Caster -->
  <link name="caster_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <sphere radius="${caster_radius}"/>
      </geometry>
      <material name="caster_material">
        <color rgba="0 0 0 1.0"/>
      </material>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <sphere radius="${caster_radius}"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="0.5"/>
      <inertia ixx="${caster_inertia_x}" ixy="0.0" ixz="0.0"
               iyy="${caster_inertia_y}" iyz="0.0" izz="${caster_inertia_z}"/>
      <origin xyz="0 0 0" rpy="0 0 0"/>
    </inertial>
  </link>

  <!-- LiDAR -->
  <link name="lidar_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder radius="0.05" length="0.05"/>
      </geometry>
      <material name="lidar_material">
        <color rgba="0.2 0.8 0.2 1.0"/>
      </material>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder radius="0.05" length="0.05"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="0.2"/>
      <inertia ixx="1e-4" ixy="0.0" ixz="0.0"
               iyy="1e-4" iyz="0.0" izz="1e-4"/>
      <origin xyz="0 0 0" rpy="0 0 0"/>
    </inertial>
  </link>

  <!-- ===================== -->
  <!-- Joints                -->
  <!-- ===================== -->

  <!-- Joint bánh trái -->
  <joint name="left_wheel_joint" type="continuous">
    <origin xyz="-${wheel_offset} ${wheel_separation/2} -${wheel_radius}" rpy="0 0 0"/>
    <parent link="body_link"/>
    <child link="left_wheel_link"/>
    <axis xyz="0 1 0"/>
    <limit effort="100" velocity="10.0"/>
    <dynamics damping="0.1" friction="0.1"/>
  </joint>

  <!-- Joint bánh phải -->
  <joint name="right_wheel_joint" type="continuous">
    <origin xyz="-${wheel_offset} ${-wheel_separation/2} -${wheel_radius}" rpy="0 0 0"/>
    <parent link="body_link"/>
    <child link="right_wheel_link"/>
    <axis xyz="0 1 0"/>
    <limit effort="100" velocity="10.0"/>
    <dynamics damping="0.1" friction="0.1"/>
  </joint>

  <!-- Joint caster -->
  <joint name="caster_joint" type="fixed">
    <origin xyz="${caster_offset} 0 -${caster_radius}" rpy="0 0 0"/>
    <parent link="body_link"/>
    <child link="caster_link"/>
  </joint>

  <!-- Joint LiDAR -->
  <joint name="lidar_joint" type="fixed">
    <!-- đặt lidar phía trước, trên nóc thân -->
    <origin xyz="${body_length/2 - 0.05} 0 ${body_height/2 + 0.02}" rpy="0 0 0"/>
    <parent link="body_link"/>
    <child link="lidar_link"/>
  </joint>

  <!-- ===================== -->
  <!-- Gazebo friction       -->
  <!-- ===================== -->

  <gazebo reference="body_link">
    <mu1>1.0</mu1>
    <mu2>1.0</mu2>
  </gazebo>

  <gazebo reference="right_wheel_link">
    <mu1>1.0</mu1>
    <mu2>1.0</mu2>
  </gazebo>

  <gazebo reference="left_wheel_link">
    <mu1>1.0</mu1>
    <mu2>1.0</mu2>
  </gazebo>

  <gazebo reference="caster_link">
    <mu1>0.00001</mu1>
    <mu2>0.00001</mu2>
  </gazebo>

  <!-- ===================== -->
  <!-- LiDAR sensor (GZ Sim) -->
  <!-- ===================== -->

  <gazebo reference="lidar_link">
    <sensor name="gpu_lidar" type="gpu_lidar">
      <!-- pose trong frame lidar_link -->
      <pose>0 0 0 0 0 0</pose>

      <!-- topic trong Gazebo (GZ) -->
      <topic>/lidar</topic>
      <update_rate>10</update_rate>
      <always_on>1</always_on>
      <visualize>true</visualize>

      <ray>
        <scan>
          <horizontal>
            <samples>360</samples>
            <resolution>1</resolution>
            <min_angle>-3.1415</min_angle>
            <max_angle>3.1415</max_angle>
          </horizontal>
          <vertical>
            <samples>1</samples>
            <resolution>1</resolution>
            <min_angle>0</min_angle>
            <max_angle>0</max_angle>
          </vertical>
        </scan>
        <range>
          <min>0.2</min>
          <max>12.0</max>
          <resolution>0.01</resolution>
        </range>
        <noise>
          <type>gaussian</type>
          <mean>0.0</mean>
          <stddev>0.01</stddev>
        </noise>
      </ray>
    </sensor>
  </gazebo>

  <!-- ===================== -->
  <!-- Gazebo plugins        -->
  <!-- ===================== -->

  <gazebo>
    <!-- Differential drive -->
    <plugin filename="gz-sim-diff-drive-system" name="gz::sim::systems::DiffDrive">
      <right_joint>right_wheel_joint</right_joint>
      <left_joint>left_wheel_joint</left_joint>
      <wheel_separation>${wheel_separation}</wheel_separation>
      <wheel_radius>${wheel_radius}</wheel_radius>
      <max_linear_acceleration>${max_linear_acceleration}</max_linear_acceleration>
      <odom_publish_frequency>100</odom_publish_frequency>
      <topic>cmd_vel</topic>
      <odom_topic>odom</odom_topic>
    </plugin>

    <!-- Joint states -->
    <plugin filename="gz-sim-joint-state-publisher-system"
            name="gz::sim::systems::JointStatePublisher">
      <topic>joint_states</topic>
      <joint_name>right_wheel_joint</joint_name>
      <joint_name>left_wheel_joint</joint_name>
    </plugin>
  </gazebo>

</robot>
